apiVersion: v1
kind: Pod
metadata:
  name: devops-final-pod
  labels:
    app: devops-final
spec:
  containers:
    - name: web
      image: devops-final-web:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
        - containerPort: 8080
        - containerPort: 22
      env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://localhost:3306/THOU_Laiheng-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "Hello@123"

    - name: db
      image: mysql:8.0
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_DATABASE
          value: "THOU_Laiheng-db"
        - name: MYSQL_ROOT_PASSWORD
          value: "Hello@123"
